[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    # "--verbose",
    "-rsx",
    "--showlocals",
    "--tb=short",
    "--strict-markers",
    "--cov=src",
    "--cov-branch", # C1カバレッジを確認
    "--cov-report=",
    "--cov-report=xml",
    # "-n=auto", # 並列でコア数分実行
]
testpaths = [
    # "tests/test_cases",
    # "tests/integration/test_cases",
    "tests/unit/test_cases",
]

# python_files = "test_*"
# python_classes = test*
# python_functions = test*

[tool.coverage.run]
relative_files = true

[tool.black]
line-length = 119
skip-string-normalization = 1
exclude = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
    | dist
)
'''

[tool.isort]
profile = "black"
line_length = 119

[tool.flake8]
max-line-length = 119
extend-ignore = "E203,"
max-complexity = 10
ignore = "E203"
select= ["C","E","F","W","B",]

[tool.mypy]
show_column_numbers  = true
show_error_context = true
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true


[tool.pydocstyle]
ignore = "D400"