parameters:
- name: python_version
  default: 3.8
- name: vm_image
  default: ubuntu-20.04

# variables:
# - group: databricks_stg
# - name: PIPELINE_ID
#   value: $(System.TeamProjectId)_$(System.DefinitionId)_$(Build.BuildNumber)
# - name: DATABRICKS_WORKSPACE_URL
#   value: $(databricks_workspace_url)
# - name: DATABRICKS_TOKEN
#   value: dapi1234
# - name: TEST_CODE_PATH_ON_DBFS
#   value: /FileStore/unit

jobs:
- job: cp_codes_to_dbfs
  pool:
    vmImage: ${{ parameters.vm_image }}
  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python ${{ parameters.python_version }}'
      inputs:
        versionSpec: ${{ parameters.python_version }}
    - task: CmdLine@2
      displayName: 'Install libraries'
      inputs:
        script: |
            pip install databricks-cli pytest pytest-cov
    - task: CmdLine@2
      displayName: 'Copy codes to databricks dbfs'
      inputs:
        script: |
          databricks fs rm -r dbfs:$(TEST_CODE_PATH_ON_DBFS)/$(PIPELINE_ID)
          databricks fs cp -r $(System.DefaultWorkingDirectory) dbfs:$(TEST_CODE_PATH_ON_DBFS)/$(PIPELINE_ID) --overwrite
      env:
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        DATABRICKS_HOST: $(DATABRICKS_WORKSPACE_URL)
